# ~/.config/starship.toml

format = """
$username\
$directory\
$git_branch\
$git_status\
$c\
$rust\
$lua\
$java\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$docker_context\
$conda\
$fill\
$cmd_duration\
$time\
$line_break\
$character
"""

[username]
show_always = true
format = '[\[$user\]]($style)'

[directory]
format = '[\[$path\]]($style)[$read_only]($read_only_style) '
read_only = '🔒'
read_only_style = 'red'
truncation_length = 5
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"DEV" = "󰲋 "

[git_branch]
symbol = ' '
format = '[\[$symbol$branch\]]($style)'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style)) '

[fill]
symbol = ' '
style = 'bold green'

[cmd_duration]
min_time = 10
style	= 'bold green'
format = '[\[$duration\]]($style)'

[time]
disabled = false
style = 'bold yellow'
time_format = "%R"
format = '[\[$time\]]($style) '

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold green)'
error_symbol = '[](bold red)'
